import Verbose.Tactics.Notations
import Verbose.Russian.Assume
import Verbose.Russian.By
import Verbose.Russian.Since
import Verbose.Russian.Claim
import Verbose.Russian.Fix
import Verbose.Russian.Lets
import Verbose.Russian.Set
import Verbose.Russian.We
import Verbose.Russian.Calc
